### ISSUE TITLE
Resurrecting the project?

### ISSUE THREAD

**Issue by hartwork** [ASKBOT/django-directory#1]
Hi @evgenyfadeev,

nice project, I thought of writing something very close. Would you accept pull requests for resurrection?

What I see is needed for a start and minimum:
- Install template files from `setup.py` so there's a chance they can be found
- Specifying supported version: Django 1.x(?) and Python 2.7 visibly
- Fixing things for Django 1.11

If anyone else comes here and wants to spin the code up for a demo / development:
```
git clone https://github.com/ASKBOT/django-directory.git
cd django-directory/
virtualenv --python=python2 py27
source py27/bin/activate
pip install Django==1.11.16
pip install .  # or ./setup.py develop 
cp -Rv directory/templates py27/lib/python2.7/site-packages/directory/  # or ln ....
django-admin startproject demo
echo $'from django.conf.urls import include\nurlpatterns.append(url("^backups/", include("directory.urls")))' >> demo/demo/urls.py
echo $'DIRECTORY_DIRECTORY = "."\nINSTALLED_APPS += ["directory"]' >> demo/demo/settings.py
( cd demo/ && ./manage.py runserver )
```

Best, Sebastian

**Comment by evgenyfadeev** [comment]
Hi Sebastian, sure feel free. Thank you!
