### ISSUE TITLE
Please push Git tag for 0.0.1

### ISSUE THREAD

**Issue by hartwork** [ASKBOT/django-directory#2]
Hi!

There's a [release `0.0.1` on PyPI](https://pypi.org/project/django-directory/0.0.1/) but there is not Git tag here. Could you add/push it?

Thanks, Sebastian

**Comment by hartwork** [comment]
It looks like c978a607797d2ebc2c138245cbcc88e8f0fdf9c2 would be the commit to tag for 0.0.1 to me.

**Comment by evgenyfadeev** [comment]
I've pushed the last one on master before merging your PR, not exact, but I don't care too much.
